In [2]:
!pip install awswrangler

Collecting awswrangler
  Using cached awswrangler-3.4.2-py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: boto3<2.0.0,>=1.20.32 in /opt/conda/lib/python3.10/site-packages (from awswrangler) (1.33.9)
Requirement already satisfied: botocore<2.0.0,>=1.23.32 in /opt/conda/lib/python3.10/site-packages (from awswrangler) (1.33.9)
Requirement already satisfied: numpy<2.0,>=1.18 in /opt/conda/lib/python3.10/site-packages (from awswrangler) (1.26.2)
Requirement already satisfied: packaging<24.0,>=21.1 in /opt/conda/lib/python3.10/site-packages (from awswrangler) (21.3)
Requirement already satisfied: pandas<3.0.0,>=1.2.0 in /opt/conda/lib/python3.10/site-packages (from awswrangler) (2.1.3)
Requirement already satisfied: pyarrow>=7.0.0 in /opt/conda/lib/python3.10/site-packages (from awswrangler) (14.0.1)
Collecting typing-extensions<5.0.0,>=4.4.0 (from awswrangler)
  Using cached typing_extensions-4.9.0-py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /opt/conda/lib/python3.10/site-packages (from boto3<2.0.0,>=1.20.32->awswrangler) (0.10.0)
Requirement already satisfied: s3transfer<0.9.0,>=0.8.2 in /opt/conda/lib/python3.10/site-packages (from boto3<2.0.0,>=1.20.32->awswrangler) (0.8.2)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /opt/conda/lib/python3.10/site-packages (from botocore<2.0.0,>=1.23.32->awswrangler) (2.8.2)
Collecting urllib3<2.1,>=1.25.4 (from botocore<2.0.0,>=1.23.32->awswrangler)
  Using cached urllib3-2.0.7-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /opt/conda/lib/python3.10/site-packages (from packaging<24.0,>=21.1->awswrangler) (3.0.9)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.10/site-packages (from pandas<3.0.0,>=1.2.0->awswrangler) (2022.1)
Requirement already satisfied: tzdata>=2022.1 in /opt/conda/lib/python3.10/site-packages (from pandas<3.0.0,>=1.2.0->awswrangler) (2023.3)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.10/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<2.0.0,>=1.23.32->awswrangler) (1.16.0)
Using cached awswrangler-3.4.2-py3-none-any.whl (396 kB)
Using cached typing_extensions-4.9.0-py3-none-any.whl (32 kB)
Using cached urllib3-2.0.7-py3-none-any.whl (124 kB)
Installing collected packages: urllib3, typing-extensions, awswrangler
  Attempting uninstall: urllib3
    Found existing installation: urllib3 2.1.0
    Uninstalling urllib3-2.1.0:
      Successfully uninstalled urllib3-2.1.0
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.3.0
    Uninstalling typing_extensions-4.3.0:
      Successfully uninstalled typing_extensions-4.3.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
spyder 5.3.3 requires pyqt5<5.16, which is not installed.
spyder 5.3.3 requires pyqtwebengine<5.16, which is not installed.
distributed 2022.7.0 requires tornado<6.2,>=6.0.3, but you have tornado 6.4 which is incompatible.
panel 0.13.1 requires bokeh<2.5.0,>=2.4.0, but you have bokeh 3.3.2 which is incompatible.
sagemaker 2.199.0 requires urllib3<1.27, but you have urllib3 2.0.7 which is incompatible.
spyder 5.3.3 requires ipython<8.0.0,>=7.31.1, but you have ipython 8.18.1 which is incompatible.
spyder 5.3.3 requires pylint<3.0,>=2.5.0, but you have pylint 3.0.2 which is incompatible.
Successfully installed awswrangler-3.4.2 typing-extensions-4.9.0 urllib3-2.0.7
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 23.3.1 -> 23.3.2
[notice] To update, run: pip install --upgrade pip

In [3]:
import pandas as pd
import awswrangler as wr
import numpy as np
from unidecode import unidecode

In [4]:
def query(query, username):
    """Retorna df da consulta ao banco de dados"""
    
    from datetime import datetime
    dt = datetime.today().strftime('%Y-%m-%d-%H-%M-%S-%f')
    path = f"s3://will-sdx-ml-platform-sagemaker-transient/{username}/{dt}"

    df = wr.athena.read_sql_query(query, 
    database=None, 
    ctas_approach=False, 
    s3_output=path)

    return df

In [5]:
query_string = '''
with base_cli as (
select distinct id_customer from
customer_curated_zone.ca_book_status_cliente
where ds_status_account = 'ACTIVE'
)
, base_transaction as (
select * from 
backoffice_curated_zone.transaction
where date(dt_data) >= date('2022-11-01')
and date(dt_data) < date('2023-11-01')
and ds_empresa = 'Will'
and upper(ds_tipo_mov) in (
    'ANTECIPACAO DE FATURA',
    'ANTECIPAÇÃO FGTS - C CLIENTE',
    'CASHBACK LOJA WILL',
    'COMPRA A VISTA',
    'COMPRA A VISTA INTER',
    'COMPRA GIFT CARD LOJA WILL',
    'COMPRA NO DEBITO',
    'COMPRA PARC LOJ_PARC ASSOC',
    'COMPRA PARCELADA EMISSOR INTERNO',
    'CREDIT VOUCHER',
    'CREDITO CASHBACK',
    'CREDITO EM CONTA',
    'CREDITO PARC FATURA',
    'CREDITO POR TRANFERENCIA',
    'DEPOSITO POR BOLETO',
    'DESC ANTECIP COMPRA',
    'DEVOLUÇÃO PIX',
    'EMPRÉSTIMO PESSOAL',
    'ENTRADA DE PARCELAMENTO',
    'ENVIO PIX CREDITO',
    'FATURA PENDENTE DE PAGAMENTO',
    'MULTA POR ATRASO',
    'PAG FATURA COM SALDO',
    'PAGAMENTO BOLETO',
    'PAGAMENTO DE TITULOS',
    'PAGAMENTO EMPRÉSTIMO PESSOAL',
    'PAGAMENTO FATURA',
    'PAGAMENTO FGTS',
    'PAGAMENTO PARCIAL',
    'PAGAMENTO RECEBIDO',
    'PAGTO DE TITULOS NO CREDITO',
    'PARC. LOJISTA MC (5X)',
    'PARCELAMENTO DE FATURA',
    'PIX ENVIADO',
    'PIX NO CREDITO',
    'PIX RECEBIDO',
    'RECARGA',
    'RECARGA DE CELULAR',
    'RECEBIDO VIA DOC',
    'SAQUE',
    'SAQUE REDE BANDEIRA',
    'TED',
    'TRANSFERENCIA DE SALDO',
    'TRANSFERENCIA ENVIADA',
    'TRANSFERENCIA RECEBIDA'
)
)
select
	 c.id_customer
	, case
		when est.ds_classificacao_nivel_2 = 'SERVICOS' then est.ds_classificacao_nivel_4
		when est.ds_classificacao_nivel_2 = 'SUPERMERCADO' then est.ds_classificacao_nivel_3
		when est.ds_classificacao_nivel_2 = 'LOJAS DE DEPARTAMENTO' then est.ds_classificacao_nivel_4
		when est.ds_classificacao_nivel_2 = 'SERVICOS DE ALIMENTACAO' then est.ds_classificacao_nivel_3
		when est.ds_classificacao_nivel_2 = 'MOBILIDADE' then est.ds_classificacao_nivel_4
		when est.ds_classificacao_nivel_2 = 'E-COMMERCE' then est.ds_classificacao_nivel_3
		when est.ds_classificacao_nivel_2 = 'SAUDE' then est.ds_classificacao_nivel_3
		when est.ds_classificacao_nivel_2 is null then 'c_'||tra.ds_tipo_mov
		when est.ds_classificacao_nivel_2 = '' then 'c_'||tra.ds_tipo_mov
		else est.ds_classificacao_nivel_2
	end as mcc
	, count(tra.ds_tipo_mov) as linhas_transaction
from base_cli c
left join base_transaction as tra on (tra.id_cliente = c.id_customer )
 left join customer_curated_zone.ca_dict_merchant_classifier as est
 	on (tra.ds_nome_estabelecimento = est.ds_nome_estabelecimento) 	
 group by 1,2

'''

In [6]:
df = query(query_string, 'flavia-costa')
df.shape

(44998279, 3)

In [7]:
df.head(5)

,id_customer,mcc,linhas_transaction
0,eff4249e-20b2-48e6-81f1-bed176e3d1fc,MOBILIDADE - TRANSPORTE PRIVADO - TAXIS,5
1,f2b8a7da-b7d5-429a-a43d-58173f29ce6f,MOBILIDADE - COMBUSTIVEL,16
2,9b942764-e32f-4c6f-a61e-12c8180e2b7b,FINANCAS,5
3,f36674d4-5c93-4ce1-9ff4-5090bf2e125b,SUPERMERCADO - ACOUGUE,5
4,509efda4-6475-414a-ad4c-b2a8a0bc0c3d,c_MULTA POR ATRASO,8

In [8]:
len(df[df['mcc'].isnull()])

2742454

In [9]:
def padronizar_mcc(df, col):
    df[col] =  df[col].str.upper() \
                    .apply(lambda x: unidecode(x)) \
                    .str.replace('- GERAL', '') \
                    .str.replace('- C CLIENTE', '') \
                    .apply(lambda x: x.rsplit('-', 1)[-1].strip()) \
                    .str.replace(' / ', '_') \
                    .str.replace(' ', '_')
    
    df[col] = np.where(df[col] == 'TELECOM', 'RECARGA', df[col])
    df[col] = np.where(df[col] == 'NAO_ESPECIFICADO', 'SERVICOS', df[col])
    df[col] = df[col].str.replace(r'.*EMPRESTIMO_PESSOAL.*', 'C_EMPRESTIMO_PESSOAL', regex=True)
    df[col] = df[col].str.replace(r'.*SAQUE.*', 'C_SAQUE', regex=True)
    df[col] = df[col].str.replace(r'.*COMPRA_A_VISTA.*', 'C_COMPRA_PARCELADA', regex=True)
    df[col] = df[col].str.replace(r'.*_PARC.*', 'C_COMPRA_A_VISTA', regex=True)
    df[col] = df[col].str.replace(r'.*FGTS.*', 'C_ANTECIPACAO_FGTS', regex=True)
    df[col] = df[col].str.replace(r'.*RECARGA.*', 'RECARGA', regex=True)
  
  
    return df

In [10]:
df['mcc'].fillna('NT', inplace = True)

In [11]:
# Ajustes do campo de MCC
#
df = padronizar_mcc(df,'mcc')

# Reagrupar os clintes
#
df = df.groupby([df['id_customer'],df['mcc']]).agg({'linhas_transaction':'sum'}).reset_index()

print(df.shape,"\n ========== \n", df['mcc'].unique())

(43162372, 3)
 ==========
 ['ATACADISTA' 'BELEZA' 'COMBUSTIVEL' 'C_PAGAMENTO_FATURA' 'C_PIX_ENVIADO'
 'C_PIX_NO_CREDITO' 'C_PIX_RECEBIDO' 'LANCHONETES' 'MULTICATEGORIA'
 'RESTAURANTES' 'VAREJISTAS' 'VESTUARIO' 'C_COMPRA_A_VISTA'
 'C_MULTA_POR_ATRASO' 'ELETRONICOS' 'APP_TRANSPORTE'
 'CONTABILIDADE_AUDITORIA_SEGUROS' 'C_PAGAMENTO_RECEBIDO' 'DENTISTAS'
 'DISTRIBUIDORES' 'EDUCACAO' 'FARMACIAS_E_DROGARIAS' 'FINANCAS'
 'LOJAS_ESPECIALIZADAS' 'MANUTENCAO_AUTOMOTIVA'
 'MATERIAL_EQUIP_ESCRITORIO' 'PADARIAS' 'PET' 'SUPRIMENTOS_PARA_CASA' 'TI'
 'DELICATESSEN' 'ENTRETENIMENTO' 'HOSPITAIS_OU_CLINICAS'
 'OUTROS_TRANSP_PUBLICO' 'REFORMAS_CONSTRUCAO' 'SERVICOS' 'TAXIS'
 'C_COMPRA_NO_DEBITO' 'BICICLETA' 'OTICAS' 'NT' 'RECARGA' 'ACADEMIAS'
 'DELIVERY' 'ACOUGUE' 'C_TRANSFERENCIA_RECEBIDA' 'ESPORTIVO' 'VIAGEM'
 'C_CREDITO_POR_TRANFERENCIA' 'ELETRICIDADE_GAS' 'SEGURO'
 'C_DEVOLUCAO_PIX' 'C_TRANSFERENCIA_DE_SALDO' 'C_DEPOSITO_POR_BOLETO'
 'ARMARINHO' 'ONIBUS' 'ATIVIDADES_IMOBILIARIAS' 'C_ANTECIPACAO_FGTS'
 'REPAROS' 'C_TRANSFERENCIA_ENVIADA' 'ESTACIONAMENTOS' 'COSMETICOS'
 'C_SAQUE' 'C_PAGTO_DE_TITULOS_NO_CREDITO' 'C_ANTECIPACAO_DE_FATURA'
 'C_ENVIO_PIX_CREDITO' 'ARQUITETURA_ENGENHARIA' 'PUBLICIDADE_ANUNCIOS'
 'C_EMPRESTIMO_PESSOAL' 'PEDAGIOS' 'C_CREDIT_VOUCHER' 'TERAPIAS'
 'LAVANDERIAS' 'C_DESC_ANTECIP_COMPRA' 'C_PAGAMENTO_DE_TITULOS'
 'CONSULTA_CREDITO' 'DOACOES' 'FUNERARIOS' 'FOTOGRAFICOS' 'ADVOCACIA'
 'EMPREGABILIDADE' 'BRINQUEDOS' 'SEGURANCA' 'APARELHOS_DIVERSOS'
 'C_COMPRA_GIFT_CARD_LOJA_WILL' 'C_RECEBIDO_VIA_DOC' 'MOBILIDADE'
 'DEDETIZACAO' 'C_FATURA_PENDENTE_DE_PAGAMENTO' 'C_PAGAMENTO_BOLETO'
 'C_CREDITO_EM_CONTA']

In [13]:
df.head()

,id_customer,mcc,linhas_transaction
0,00000415-7e62-4521-8214-8b83c88d7886,ATACADISTA,2
1,00000415-7e62-4521-8214-8b83c88d7886,BELEZA,2
2,00000415-7e62-4521-8214-8b83c88d7886,COMBUSTIVEL,5
3,00000415-7e62-4521-8214-8b83c88d7886,C_PAGAMENTO_FATURA,9
4,00000415-7e62-4521-8214-8b83c88d7886,C_PIX_ENVIADO,9

In [18]:
len(df.query('mcc == "NT"')['id_customer'].unique())

2742454

In [31]:
df_agg = df.query('mcc != "NT"').groupby(df['id_customer']).agg({'mcc':'count'}).reset_index()

In [20]:
df_agg.head()

                            id_customer  mcc
0  00000415-7e62-4521-8214-8b83c88d7886   12
1  0000073e-63eb-449d-8843-c96fcfd0e4c7    9
2  0000109c-9fd2-49c5-a690-a83c4f0dd191    5
3  000010cc-3539-4a65-87c9-f32b35a1a442   24
4  000015a4-51cd-41d5-b95a-f0c444e464af   23

In [32]:
df_agg = df_agg.rename(columns = {'mcc':'qtd_cat_real'})

In [33]:
df_agg['qtd_cat_real'].value_counts()

qtd_cat_real
1     228437
11    159490
12    159396
10    158211
13    157714
9     156004
14    155430
8     154701
7     153482
6     151108
15    150820
5     147776
3     144643
16    143684
2     141347
4     140720
17    135161
18    124904
19    114254
20    102182
21     89684
22     76255
23     64097
24     52914
25     42472
26     33247
27     25476
28     18601
29     13452
30      9720
31      6628
32      4595
33      3011
34      1919
35      1220
36       753
37       479
38       292
39       167
40       100
41        52
42        28
43        15
44        11
46         5
45         5
49         1
51         1
58         1
53         1
48         1
Name: count, dtype: int64

In [36]:
df_zero = pd.DataFrame()

In [37]:
df_zero['id_customer'] = df.query('mcc == "NT"')['id_customer'].unique()

In [38]:
df_zero['qtd_cat_real'] = 0

In [39]:
df_zero.head()

                            id_customer  qtd_cat_real
0  00003373-defc-403c-bee4-9d9e39329da1             0
1  000033ae-acd6-4a74-9c3e-0dc5334be66b             0
2  000036be-b8a3-493d-a232-ac608fd646cc             0
3  00005c62-1f9e-414f-9d03-0b41ca7b919a             0
4  000061d9-fe27-4ff2-9a4c-86bf359bc9e8             0

In [40]:
df_agg = pd.concat([df_zero, pd.DataFrame(df_agg)], ignore_index=True)

In [41]:
df_agg.head()

                            id_customer  qtd_cat_real
0  00003373-defc-403c-bee4-9d9e39329da1             0
1  000033ae-acd6-4a74-9c3e-0dc5334be66b             0
2  000036be-b8a3-493d-a232-ac608fd646cc             0
3  00005c62-1f9e-414f-9d03-0b41ca7b919a             0
4  000061d9-fe27-4ff2-9a4c-86bf359bc9e8             0

In [42]:
df_agg['qtd_cat_real'].value_counts()

qtd_cat_real
0     2742454
1      228437
11     159490
12     159396
10     158211
13     157714
9      156004
14     155430
8      154701
7      153482
6      151108
15     150820
5      147776
3      144643
16     143684
2      141347
4      140720
17     135161
18     124904
19     114254
20     102182
21      89684
22      76255
23      64097
24      52914
25      42472
26      33247
27      25476
28      18601
29      13452
30       9720
31       6628
32       4595
33       3011
34       1919
35       1220
36        753
37        479
38        292
39        167
40        100
41         52
42         28
43         15
44         11
46          5
45          5
49          1
51          1
58          1
53          1
48          1
Name: count, dtype: int64

In [43]:
query_string = '''

with eventos as (
	select 
	id_customer
	, count(distinct dt_event) as nr_acessos
	from customer_curated_zone.ca_analitico_frontend
	where lower(ds_event_name) <> 'login_knownuser'
	and lower(ds_event_name) <> 'insert_textfield_password_loginknownuser'
	and lower(ds_event_name) <> 'home'
	and lower(ds_event_name) <> 'click_box_tracking_card_home'
	and cast(dt_event as DATE) >= date('2023-01-01')
	and cast(dt_event as DATE) < date('2023-11-01')
	group by 1
)
, rentabilidade_conta as (
select 
id_customer
, sum(vl_rentabilidade_min) as rentabilidade_conta
from customer_curated_zone.ca_model_rent_conta_simples
where ds_yearmonth_rent_calc = '2023-10'
group by 1
)
, rentabilidade_credito as (
select 
id_customer
, sum(ltv) as rentabilidade_credito
, sum(rec_servicos + rec_itr + rec_recarga) as receitas
from public.rentabilidade_cartoes_isabelle_dias
where mesref = '2023-10'
group by 1
)
select
c.id_customer
, nr_acessos
, rentabilidade_credito
, receitas
, rentabilidade_conta
from rentabilidade_credito c
left join eventos e on (e.id_customer = c.id_customer)
left join rentabilidade_conta co on (co.id_customer = c.id_customer)

'''

In [44]:
df_2 = query(query_string, 'flavia-costa')

In [45]:
df_2.shape

(4269312, 5)

In [46]:
df_3 = df_agg.join(df_2.set_index('id_customer'), on = 'id_customer', how = 'left')

In [47]:
df_3.head()

,id_customer,qtd_cat_real,nr_acessos,rentabilidade_credito,receitas,rentabilidade_conta
0,00003373-defc-403c-bee4-9d9e39329da1,0,<NA>,NaN,NaN,NaN
1,000033ae-acd6-4a74-9c3e-0dc5334be66b,0,<NA>,0.0,0.0,NaN
2,000036be-b8a3-493d-a232-ac608fd646cc,0,<NA>,0.0,0.0,-27.65
3,00005c62-1f9e-414f-9d03-0b41ca7b919a,0,<NA>,0.0,0.0,NaN
4,000061d9-fe27-4ff2-9a4c-86bf359bc9e8,0,<NA>,NaN,NaN,NaN

In [48]:
df_3['nr_acessos'].sum()

241237497

In [49]:
df_agg2 = df_3.groupby('qtd_cat_real') \
.agg({'id_customer':['count'], 'nr_acessos':['sum'], \
      'rentabilidade_credito':['sum'], \
      'receitas':['sum'], \
     'rentabilidade_conta':['sum']
     })

In [50]:
df_agg2

,id_customer,nr_acessos,rentabilidade_credito,receitas,rentabilidade_conta
,count,sum,sum,sum,sum
qtd_cat_real,,,,,
0,2742454,4206711,2.548338e+03,5.248504e+04,-4.009390e+06
1,228437,1520187,-3.935460e+06,1.060273e+06,-1.179496e+05
2,141347,2606915,-1.150935e+06,7.377998e+05,-4.844325e+05
3,144643,3761045,-6.466174e+05,9.806999e+05,-2.891238e+05
4,140720,4597317,-5.016235e+05,1.167169e+06,-1.260171e+05
5,147776,5617764,-3.301924e+05,1.316596e+06,-3.455194e+04
6,151108,6444227,-2.960419e+05,1.399203e+06,-1.090337e+03
7,153482,7235141,-3.688533e+05,1.513945e+06,-8.553927e+02
8,154701,8060502,-1.547773e+05,1.571067e+06,1.296954e+03
9,156004,8891278,-2.235618e+04,1.670982e+06,-3.002185e+02
10,158211,9794108,2.154792e+05,1.746945e+06,-2.812654e+02
11,159490,10630253,2.934576e+05,1.821033e+06,-9.454487e+02
12,159396,11461953,5.551873e+05,1.883343e+06,-7.835830e+02
13,157714,12121031,7.750438e+05,1.923282e+06,-6.815540e+02
14,155430,12694680,1.084639e+06,1.970472e+06,-7.440277e+02
15,150820,13035460,1.183103e+06,1.982013e+06,-9.260610e+02
16,143684,13184273,1.350917e+06,1.965595e+06,-9.250364e+02
17,135161,13058334,1.371553e+06,1.939805e+06,-4.090199e+02
18,124904,12703665,1.499707e+06,1.882413e+06,-1.072015e+03
19,114254,12111650,1.623814e+06,1.792650e+06,-6.853650e+02
20,102182,11322068,1.740198e+06,1.679127e+06,-3.904469e+02
21,89684,10305139,1.699428e+06,1.564214e+06,-2.305118e+02
22,76255,9091563,1.566366e+06,1.420968e+06,-2.790513e+02
23,64097,7886150,1.477630e+06,1.277820e+06,-4.093383e+02
24,52914,6698971,1.319180e+06,1.111171e+06,-9.192973e+00
25,42472,5528087,1.216978e+06,9.517989e+05,1.974334e+00
26,33247,4443294,1.007404e+06,8.016285e+05,1.899111e+02
27,25476,3467728,7.945301e+05,6.676400e+05,6.986722e+01
28,18601,2580183,6.943695e+05,5.246760e+05,9.905918e+01
29,13452,1901259,5.143459e+05,3.971213e+05,7.834384e+01
30,9720,1404225,4.218030e+05,3.158059e+05,3.917364e+01
31,6628,965256,3.242359e+05,2.327289e+05,2.569994e+02
32,4595,671253,2.458139e+05,1.763199e+05,-5.126813e+01
33,3011,457458,1.472136e+05,1.266909e+05,0.000000e+00
34,1919,286531,1.108332e+05,8.872106e+04,0.000000e+00
35,1220,185196,7.004233e+04,5.878145e+04,0.000000e+00
36,753,115590,4.360705e+04,4.074013e+04,0.000000e+00
37,479,76745,3.593996e+04,2.840351e+04,0.000000e+00
38,292,48220,2.166272e+04,1.807324e+04,0.000000e+00
39,167,27775,1.214578e+04,1.087399e+04,0.000000e+00
40,100,17089,1.124418e+04,5.937669e+03,0.000000e+00
41,52,9269,3.919894e+03,3.956386e+03,0.000000e+00
42,28,4687,1.649584e+03,2.381733e+03,0.000000e+00
43,15,2458,1.080424e+03,2.266108e+03,0.000000e+00
44,11,1984,1.664712e+03,1.429644e+03,0.000000e+00
45,5,817,4.382676e+02,9.961955e+02,0.000000e+00
46,5,1115,6.125055e+02,8.423088e+02,0.000000e+00
48,1,174,2.971411e+02,7.358779e+02,0.000000e+00
49,1,202,2.714926e+02,3.898238e+02,0.000000e+00
51,1,179,4.750940e+02,2.924444e+02,0.000000e+00
53,1,127,8.930824e+01,2.236320e+02,0.000000e+00
58,1,211,1.154997e+03,1.543982e+03,0.000000e+00

In [51]:
df_agg2.to_csv('simulacao_recom.csv')