In [1]:
import pandas as pd
import numpy as np
import aux.acessos as ac
import datetime

In [2]:
query = "select * from growth_curated_zone.proposal_general where dt_approval is not null limit 10000"

base = ac.df_athena('flavia-costa', query)

In [3]:
base['safra_ano'] = base['dt_approval'].astype("string").str[:4].astype("int")
base['safra'] = base['dt_approval'].astype("string").str[:7].str.replace('-','').astype("int")

In [5]:
#amostra da base inteira
amostragem = 0.2

#definindo pesos por safra
def weight_match(safra):
    if   safra >= 201901 and safra < 202001: #ano de 2019
        matchVar = 0.1
    elif safra >= 202001 and safra < 202101: #ano de 2020
        matchVar = 0.2
    elif safra >= 202101 and safra < 202106: #ano de 2021-S1
        matchVar = 0.1
    elif safra >= 202106: #ano de 2021-S2
        matchVar = 0.6
    else:
        matchVar = 0
    return matchVar

In [6]:
base['weight'] = base.apply(lambda x: weight_match(x['safra']), axis=1) 
base['weight_final'] = base['weight'] * amostragem
base['qtde_max'] = base['weight_final'] * len(base)
base['aleat'] = np.random.random((len(base),1))
base['rank'] = base['aleat'].rank()
base_amostra_1 = base.query('rank <= qtde_max')

In [10]:
base.head()

,ds_origin,id_proposal,dt_created_user,dt_created_proposal,dt_disapproval,dt_approval,cd_cpf,nr_cellphone,ds_email,nm_person,...,nm_locality,nm_neighborhood,nr_zip_code,safra_ano,safra,weight,weight_final,qtde_max,aleat,rank
0,will,b352bf20-01b2-48bb-8040-4514b6cb08b6,2021-12-14 14:03:27.071,2021-12-14 14:12:08.127,None,2021-12-17 09:22:49.400,07040409488,5584996795208,henrriike@gmail.com,HENRIQUE MARQUES DE SOUSA,...,Portalegre,Centro,59810000,2021,202112,0.6,0.12,1200.0,0.539428,5411.0
1,will,d75c2033-b63b-421d-9be3-3e20a7b850d6,2022-02-14 14:12:10.917,2022-02-14 14:13:35.302,None,2022-02-15 16:04:00.140,05587552594,5575988517314,wirantuxa@yahoo.com.br,UIRAN ERNAN VIEIRA PADILHA,...,Feira de Santana,Parque Ipê,44054056,2022,202202,0.6,0.12,1200.0,0.477324,4769.0
2,will,02911f91-b730-43f0-8a7e-5feaf42746f7,2022-02-14 12:28:15.050,2022-02-14 12:28:55.163,None,2022-02-15 12:51:11.749,01310255385,5588998133458,celmasilva0608@gmail.com,CELMA HOLANDA DA SILVA,...,Acaraú,Sítio buriti,62580000,2022,202202,0.6,0.12,1200.0,0.731632,7324.0
3,will,3288e518-e724-4842-8bd7-5c4c587b9d00,2022-06-01 19:26:15.725,2022-06-01 19:37:57.634,None,2022-06-03 08:34:02.999,06267715957,5548984697069,carlinhasoto14@gmail.com,CARLA ANDREA DA SILVEIRA SOTO,...,São José,Forquilhas,88107644,2022,202206,0.6,0.12,1200.0,0.846028,8467.0
4,will,23f74ed7-299a-4345-8276-4907284a783e,2022-01-04 13:38:15.611,2022-01-04 13:39:27.104,None,2022-02-26 20:38:30.079,38263284856,5511972407875,comercecp@gmail.com,CIBELE REGINA COMERCE FRANCISCO,...,Osasco,Piratininga,06230150,2022,202202,0.6,0.12,1200.0,0.290731,2884.0

In [12]:
len(base_amostra_1)

1176

In [13]:
base_amostra_1[['safra', 'rank']].groupby('safra').count()

        rank
safra
202012     1
202101     3
202103     4
202104     1
202105     1
202106     5
202107    10
202108     2
202112    71
202201   154
202202   266
202203   254
202204   156
202205   152
202206    96

In [14]:
base[['safra', 'rank']].groupby('safra').count()

        rank
safra
202010     1
202011     4
202012    36
202101    21
202102    51
202103    92
202104    53
202105    82
202106    42
202107    66
202108    22
202112   683
202201  1303
202202  2086
202203  2229
202204  1228
202205  1187
202206   814

In [ ]:
#DEIXANDO A VARIÁVEL DE SAFRA NO FORMATO NUMERICO
data_final['safra'] = data_final['ds_safra'].astype("string").str[:7].str.replace('-','').astype("int")

#amostra da base inteira
amostragem = 0.2

#definindo pesos por safra
def weight_match(safra):
    if   safra >= 201901 and safra < 202001: #ano de 2019
        matchVar = 0.1
    elif safra >= 202001 and safra < 202101: #ano de 2020
        matchVar = 0.2
    elif safra >= 202101 and safra < 202106: #ano de 2021-S1
        matchVar = 0.1
    elif safra >= 202106: #ano de 2021-S2
        matchVar = 0.6
    else:
        matchVar = 0
    return matchVar

#definindo categoria por safra
def weight_match_cat(safra):
    if   safra >= 201901 and safra < 202001: #ano de 2019
        matchVar_cat = '2019'
    elif safra >= 202001 and safra < 202101: #ano de 2020
        matchVar_cat = '2020'
    elif safra >= 202101 and safra < 202106: #ano de 2021-S1
        matchVar_cat = '2021S1'
    elif safra >= 202106: #ano de 2021-S2
        matchVar_cat = '2021S2_22'
    else:
        matchVar_cat = ''
    return matchVar_cat


### Calculando o peso de cada safra ~ Definindo o limite máximo por peso
data_final['weight'] = data_final.apply(lambda x: weight_match(x['safra']), axis=1) 
data_final['weight_final'] = data_final['weight'] * amostragem
data_final['qtde_max'] = data_final['weight_final'] * len(data_final)

### Definindo grupo de amostra por safra
data_final['safra_cat'] = data_final.apply(lambda x: weight_match_cat(x['safra']), axis=1) 

### Definindo o aleatorio para cada safra

# Tamanho de amostra por safra
data_c_safra = data_final.groupby('safra_cat').agg(count_safra = ('cpf','count'))
data_c_safra.reset_index(level=0, inplace=True)
data_c_safra
data_final_count = data_final.merge(data_c_safra, how='left', on='safra_cat')

# Criando aleatorio para cada safra
data_aleat_list = []

for safra in data_final_count.safra_cat.unique():
    data_subset = data_final_count[data_final_count.safra_cat == safra][['cpf','safra_cat']]
    data_subset['aleat'] = np.random.random((len(data_subset),1))
    data_aleat_list.append(data_subset)
data_aleat = pd.concat(data_aleat_list)
data_aleat = data_aleat.sort_values(by = 'cpf', ascending=True).reset_index().drop(columns='index')

data_final = data_final.sort_values(by = 'cpf', ascending=True).reset_index().drop(columns='index')

data_final['aleat'] = data_aleat['aleat']
#data_final = data_final.merge(data_aleat, how='left', on='safra') ## Problema de memória

# Criando ranking por safra
data_final['rank'] = data_final.groupby('safra_cat')['aleat'].rank()
data_final['rank_int'] = data_final['rank'].astype(int) ### Teste para mudança de formato

base_amostra_1 = data_final[data_final.rank_int <= data_final.qtde_max]